apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: order-db
  labels:
    app: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          image: mauricio1998/order-db:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017