apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: fiap
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
    - port: 27017
      targetPort: 27017
      name: order-db
  type: ClusterIP