apiVersion: v1
data:
  config.yaml: |
    server:
      port: 3010
      paymentIntegrationHost: payment-service.fiap.svc.cluster.local:3011/
    db:
      connectionString: mongodb://root:password@order-db.fiap.svc.cluster.local:27017/
kind: ConfigMap
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: fiap
