apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mauricio1998/order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          volumeMounts:
            - name: order-service
              subPath: config.yaml
              mountPath: /go/app/config.yaml
      volumes:
        - name: order-service
          configMap:
            name: "order-service"